export const designTokens = {
    color: {
        primary: '#12FFBB',
        secondary: '#334049',
        background: '#F4FBF9',
        border: '#C5D1E2',
        white: '#FFFFFF',
        gray: '#EDEDED',
        darktGray: '#8C8C8C',
        selected: '#008961',
        selectedLight: '#00B176', 
        boxShadow: 'rgba(0, 0, 0, 0.10)',
        cardShadow: '0 8px 22px rgba(0, 0, 0, 0.25)',
        text: '#334049',
        error: '#F11D00',
        success: '#10C200',
        alert: '#FFDB0F',
    },
    spacing: {
        tiny: '4px',
        small: '8px',
        medium: '16px',
        mediumLarge: '24px',
        large: '32px',
    },
    borderRadius: {
        small: '4px',
        smallMedium: '6px',
        medium: '8px',
        large: '12px',
    },
    font: {
        family: 'Poppins, sans-serif',
        size: {
            small: '12px',
            smallMedium: '14px',
            medium: '16px',
            mediumLarge: '18px',
            large: '24px',
            extraLarge: '32px',
        },
        weight: {
            light: 300,
            regular: 400,
            medium: 500,
            semiBold: 600,
            bold: 700,
            xBold: 800,
        },
        lineHeight: {
            small: '16px',
            medium: '24px',
            large: '32px',
        },
    }
}
